### ISSUE TITLE
Diseño de Mockup Web 3.0

### ISSUE THREAD

**Issue by Rufino07** [SistemasTecTlaxiaco/actividad-5-diseno-de-mockup-para-dapp-team-pro-1#1]
[DISEÑO DE INTERFAZ DE USUARIO (MOCKUP).pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-diseno-de-mockup-para-dapp-team-pro-1/files/14671872/DISENO.DE.INTERFAZ.DE.USUARIO.MOCKUP.pdf)

**Comment by yanet02** [comment]
**Calificación en base a la rúbrica:**

Portada 25
procedimiento 25
firguras e ilustraciones: 25
resultado y conclusiones: 22
TOTAL=97
Calificación Final: **19.4/_20_**
Falto resultados lo demás bien hecho.

**Comment by josealfredo79** [comment]
Aqui el detalle del mockup es que registra y se inicia sesion con un usuario y contraseña...con las dapp y con el protocolo de Near se utiliza una billetera por favor checar y mejorar el prototipo...por favor...

**Comment by Elisahadad** [comment]
[DISEÑO DE INTERFAZ DE USUARIO (MOCKUP).pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-diseno-de-mockup-para-dapp-team-pro-1/files/14936494/DISENO.DE.INTERFAZ.DE.USUARIO.MOCKUP.pdf)

**Comment by josealfredo79** [comment]
Calificacion..19
